### ISSUE TITLE
java.lang.NoClassDefFoundError: java.util.Objects on older android versions

### ISSUE THREAD

**Issue by krzysztof113** [yihleego/banana#4]
I got "java.lang.NoClassDefFoundError: java.util.Objects" on older android versions.
Any chance for a workaround?

Here's background:
https://stackoverflow.com/questions/37778644/java-lang-noclassdeffounderror-java-util-objects

**Comment by yihleego** [comment]
It has been fixed, please upgrade to the latest version.

## Maven
```xml
<dependency>
    <groupId>io.leego</groupId>
    <artifactId>banana</artifactId>
    <version>1.2.1</version>
</dependency>
```

## Gradle
```xml
implementation 'io.leego:banana:1.2.1'
```

thx a lot.
